version: '3.4'

x-cost_metrics:
  &cost_metrics
  build:
    context: .
    dockerfile: Dockerfile

services:

  cost_metrics_worker:
    <<: *cost_metrics

  cost_metrics_dashboard:
    <<: *cost_metrics

  cost_metrics_server:
    <<: *cost_metrics
