version: '3.4'

x-cost_metrics:
  &cost_metrics
  image: shchelokovskiy/cost_metrics:latest
  restart: always
  environment:
    - SQL_SERVER
    - SQL_DATABASE
    - SQL_USER
    - SQL_PASSWORD
    - WF_LOGIN_HEADER
    - WF_LOGIN_PASSWORD
    - WF_LOGIN
    - WF_PASSWORD
    - WF_ENDPOINT
    - SERVER_PORT
    - FLOWER_PORT
    - CORS_ORIGINS
    - QUERY_SERVICE
    - REDIS_SERVICE=cost_metrics_redis
    - REDIS_PORT
    - REDIS_DB
    - ADVANCED_MODE_CODE
    - ADVANCED_MODE_NAME
    - CELERY_BROKER_URL=redis://cost_metrics_redis:6379/0
    - CELERY_RESULT_BACKEND=redis://cost_metrics_redis:6379/0
    - SQLITE_DATABASE=${DB_HOME}/db
    - LD_LIBRARY_PATH=/usr/lib #https://stackoverflow.com/questions/49920444/upgrading-sqlite3-version-used-in-python3-on-linux
    - PRODUCTION
    - RECALCULATE_FROM_THE_BEGINNING

services:
  cost_metrics_dashboard:
    <<: *cost_metrics
    hostname: cost_metrics_dashboard
    container_name: cost_metrics_dashboard
    command: celery --app=worker flower --port=${FLOWER_PORT}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${FLOWER_PORT}/healthcheck"
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    depends_on:
      cost_metrics_redis:
        condition: service_healthy

  cost_metrics_worker:
    <<: *cost_metrics
    hostname: cost_metrics_worker
    container_name: cost_metrics_worker
    command: celery --app=worker worker --beat --loglevel=INFO --concurrency=7
    volumes:
      - cost_metrics-volume:${DB_HOME}
    depends_on:
      cost_metrics_redis:
        condition: service_healthy
      cost_metrics_dashboard:
        condition: service_healthy

  cost_metrics_server:
    <<: *cost_metrics
    hostname: cost_metrics_server
    container_name: cost_metrics_server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: uvicorn server:app --host 0.0.0.0 --port ${SERVER_PORT} --log-level critical
    volumes:
      - cost_metrics-volume:${DB_HOME}

  cost_metrics_redis:
    image: redis/redis-stack:latest
    hostname: cost_metrics_redis
    container_name: cost_metrics_redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - cost_metrics-volume:/data
    ports:
      - "${REDIS_INSIGHT_PORT}:8001"

volumes:
  cost_metrics-volume:
